apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: study-buddy
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: study-buddy
  source:
    repoURL: https://github.com/yuvanist/ai-study-buddy.git
    targetRevision: HEAD
    path: k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

